[tool.poetry]
name = "discogs-tag-updater"
version = "0.2.0"
description = "Updates genre, year and image of .mp3 and .flac files based on title, artist using the Discogs database."
authors = ["Aesir"]

[tool.poetry.dependencies]
python = "^3.7"
colorama = "^0.4.4"
discogs-client = "2.2.2"
fuzzywuzzy = "0.17.0"
mutagen = "1.42.0"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
