[tool.poetry]
name = "discogs-tag-updater"
version = "0.1.0"
description = ""
authors = ""

[tool.poetry.dependencies]
python = "^3.7"
mutagen = "1.42.0"
discogs-client = "2.2.2"
fuzzywuzzy = "0.17.0"
colorama = "^0.4.4"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
