[tool.poetry]
name = "discogs-tag-updater"
version = "1.3.0"
description = "Updates genre, year and covers tags of .mp3 and .flac files based on track title and artist using the Discogs database."
authors = ["Aesir", "bolinocroustibat"]

[tool.poetry.dependencies]
python = "^3.7"
colorama = "^0.4.4"
discogs-client = "2.3.0"
fuzzywuzzy = "^0.18.0"
mutagen = "^1.45.1"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
